---
abstract: 'Base class for minimal Value Object classes'
author:
  - 'G. Wade Johnson <gwadej@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Value
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  perl: 5.01
  version: 0
version: 0.01
